version: '3.8'

services:
  app:
    build: .
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    tty: true
    restart: always
    environment:
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mysecretpassword
      DB_HOST: postgres
    env_file:
      - .env
    depends_on:
      - postgres
    
  postgres:
    image: postgres:15.3
    ports:
     - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  pgdata:
